apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: torsw-peer
spec:
  peerIP: 192.168.4.1
  asNumber: 65116
  password:
    secretKeyRef:
      name: tor-peer
      key: tor-pw
  nodeSelector:
    node-role.kubernetes.io/worker == "true"