apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  asNumber: 64700
  serviceClusterIPs:
  - cidr: 10.43.0.0/16
  serviceLoadBalancerIPs:
  - cidr: 192.168.5.0/24
  listenPort: 179
  communities:
  - name: bgp-service-community
    value: 64700:300:100
  prefixAdvertisements:
  - cidr: 192.168.5.0/24
    communities:
    - bgp-service-community
    - 64700:120